version: "3.6"
services:
  islasgeci:
    build:
      context: .
      dockerfile: Dockerfile
    image: islasgeci/geci_data:latest
    command: bash
    volumes:
      - $PWD:/workdir
  external_data_api:
    image: islasgeci/geci_data:latest
    volumes:
      - $PWD:/workdir
    ports:
      - "1000:10000"
