version: "3.1"
services:
  islasgeci:
    build:
      context: .
      dockerfile: Dockerfile
    image: islasgeci/geci_data:latest
    command: bash
    volumes:
      - $PWD:/workdir
  core_api:
    build: .
    container_name: "core-api-container"
    ports:
      - "8000:15400"
    volumes:
      - ./geci_data:/geci_data
