version: "3.6"
services:
  app_develop:
    image: islasgeci/internal_download:latest
    container_name: "app-develop-container"
    environment:
      BITBUCKET_USERNAME: $BITBUCKET_USERNAME
      BITBUCKET_PASSWORD: $BITBUCKET_PASSWORD
    entrypoint: ["streamlit", "run", "src/streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]
    ports:
      - "8502:8501"
    volumes:
      - $PWD/geci-internal-download:/workdir
      - $PWD/tabular_data_packages:/workdir/data
    networks:
      - geci
  core_api:
    build: .
    container_name: "core-api-container"
    volumes:
      - $PWD/geci-data:/workdir
    networks:
      - geci

networks:
  geci:
