version: "3.6"
services:
  islasgeci:
    build:
      context: .
      dockerfile: Dockerfile
    image: islasgeci/geci_data:latest
    command: bash
    volumes:
      - $PWD:/workdir
  external_data_api:
    image: islasgeci/geci_data:latest
    entrypoint: ["uvicorn", "geci_data.api:app", "--host", "0.0.0.0", "--port", "10000"]
    volumes:
      - $PWD:/workdir
    ports:
      - "1000:10000"
